# templates_config.py
# Путь к .docx шаблонам остаётся относительным (папка input/)
TEMPLATES = [
    {
        "path": "input/дневник.docx",
        "out":  "Дневник_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "student":  "ФИО",
            "group": "Группа",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "kurs": "Курс",
            "kafedra": "Кафедра",
            "fio": "ФИО",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "initialStudent": "РасшифровкаСтудента",
            "RukProfOrg": "РукПрофОрг",
            "RukOrg": "РукВУЗ"
        }
    },
    {
        "path": "input/договор новый тз.docx",
        "out":  "Договор_новый_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",   
            "RukOrgFIO": "РукВУЗФИО",
            "burnOrgDate": "ДатаСозданияОрганизации",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ОргИНН",
            "dolj": "Должность",
            "org_adress": "АдрессОрганизации",
            "strukPodr": "СтруктурноеПодразделение",
            "kab": "КабинетНомер",
            "group": "Группа",
            "kafedra": "Кафедра",
            "fio": "ФИО",
            "RukProfOrg": "РукПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
        }
    },
    {
        "path": "input/договор старый тз.docx",
        "out":  "Договор_старый_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",   
            "RukOrgFIO": "РукВУЗФИО",
            "burnOrgDate": "ДатаСозданияОрганизации",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ОргИНН",
            "dolj": "Должность",
            "org_adress": "АдресОрганизации",
            "strukPodr": "СтруктурноеПодразделение",
            "kab": "КабинетНомер",
            "group": "Группа",
            "kafedra": "Кафедра",
            "fio": "ФИО",
            "RukProfOrg": "РукПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
        }
    },
    {
        "path": "input/Доп.сведения.docx",
        "out":  "Доп.сведения_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "RukOrgFIO": "РукВУЗФИО",
            "burnOrgDate": "ДатаСозданияОрганизации",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ОргИНН",
            "dolj": "Должность",
            "org_adress": "АдресОрганизации",
            "strukPodr": "СтруктурноеПодразделение",
            "kab": "КабинетНомер",
            "group": "Группа",
            "kafedra": "Кафедра",
            "fio": "ФИО",
            "fioRP": "ФИОвРП",
            "RukProfOrg": "РукПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "naprPodg": "направлениеПодготовки",
            "profile": "ПрофильОбучения",
            "SvedOFormStudy": "СведенияОФормеОбучения",
            "SvedOProhObuch": "СведенияОПрохЧастиОбрПрог",
            "SvedOProhUskObuch": "СведОПрохУскорОбуч",
            "initialStudent": "РасшифровкаСтудента",
        }
    },
    {
        "path": "input/Задание на ВКР - 1.docx",
        "out":  "Задание_на_ВКР - 1_{ФИО}_{Группа}.docx",
        "fields": {
            "naprPodg": "направлениеПодготовки",
            "kurs": "Курс",
            "group": "Группа",
            "studyForm": "формыОбучения",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "fio": "ФИО",
            "fioDP": "ФИОДП",
            "initialRukVRK": "ИницРукВКР",
            "srokSdachiVRK": "СрокСдачиВКР"
        }
    },
    {
        "path": "input/Задание на ВКР - 2.docx",
        "out":  "Задание_на_ВКР - 2_{ФИО}_{Группа}.docx",
        "fields": {
            "fioDP": "ФИОДП",
            "group": "Группа",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "initialRukVRK": "ИницРукВКР",
            "initialStudent": "РасшифровкаСтудента",
        }
    },
    {
        "path": "input/Заявление на АП - 2.docx",
        "out":  "Заявление на АП - 2_{ФИО}_{Группа}.docx",
        "fields": {
            "zavKaf": "ЗаведующийКафедрой",
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "naprPodg": "НаправлениеПодготовки",
            "FIONauchRuk": "ФИОНаучРук",
            "kafedraRP": "КафедраРП",
            "doljNauchRuk": "ДолжНаучРук",
            "fio": "ФИО",
        }
    },
    {
        "path": "input/Заявление на размещение в ЭБС.docx",
        "out":  "Заявление на размещение в ЭБС_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "naprPodg": "НаправлениеПодготовки",
            "fio": "ФИО",
            "kafedra": "Кафедра",
            "Date": "СегодняшняяДата"
        }
    },
    {
        "path": "input/заявление.docx",
        "out":  "заявление_{ФИО}_{Группа}.docx",
        "fields": {
            "zavKaf": "ЗаведующийКафедрой",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "profile": "ПрофильОбучения",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "strukPodr": "СтруктурноеПодразделение",
            "RukProfOrg": "РукПрофОрг",
            "dolj": "Должность",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "Date": "СегодняшняяДата",
            "fioRukProfOrg": "ФИОРукПрофОрг",
            "fio": "ФИО",
        }
    },
    {
        "path": "input/индивидуальное задание.docx",
        "out":  "индивидуальное задание_{ФИО}_{Группа}.docx",
        "fields": {
            "workObject": "ОбъектРаботы",
            "pr_type": "ТипПрактики",
            "kafedra": "Кафедра",
            "fioDP": "ФИОДП",
            "group": "Группа",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "initialRukVRK": "ИницРукВКР",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "org_name": "БазаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "RukProfOrg": "РукПрофОрг",
            "RukOrg": "РукВУЗ",
            "initialStudent": "РасшифровкаСтудента",
            "Date": "СегодняшняяДата"
        }
    },
    {
        "path": "input/Каникулы.docx",
        "out":  "Каникулы_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "naprPodg": "направлениеПодготовки",
            "profile": "ПрофильОбучения",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "fio": "ФИО",
            "initialStudent": "РасшифровкаСтудента",
            "FStud": "ФамилияСтудента"
        }
    },
    {
        "path": "input/Ознакомительный лист.docx",
        "out":  "Ознакомительный_лист_{ФИО}_{Группа}.docx",
        "fields": {
            "initialStudent": "РасшифровкаСтудента",
            "FStud": "ФамилияСтудента",
            "NStud": "ИмяСтудента",
            "OStud": "ОтчествоСтудента",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "initialStudent": "РасшифровкаСтудента",
        }
    },
    {
        "path": "input/совместный график.docx",
        "out":  "совместный_график_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "pr_type": "ТипПрактики",
            "vidPractikiPR": "ВидПрактикаВРП",
            "kurs": "Курс",
            "srokPrak11": "Срок11",
            "srokPrak12": "Срок12",
            "srokPrak13": "Срок13",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "initialStudent": "РасшифровкаСтудента",
            "RukProfOrg": "РукПрофОрг",
            "RukOrg": "РукВУЗ",
            "org_name": "БазаПрактики",
        }
    },
    {
        "path": "input/Титул ВКР.docx",
        "out":  "Титул_ВКР_{ФИО}_{Группа}.docx",
        "fields": {
            "naprPodg": "направлениеПодготовки",
            "group": "Группа",
            "studyForm": "формыОбучения",
            "fio": "ФИО",
            "zavKaf": "ЗаведующийКафедрой",
            "year": "год",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "initialRukVRK": "ИницРукВКР",
        }
    },
    {
        "path": "input/титул отчета.docx",
        "out":  "титул_отчета_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "fioRukProfOrg": "ФИОРукПрофОрг",
            "RukOrgFIO": "РукВУЗФИО",
            "group": "Группа",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "fio": "ФИО",
            "year": "год",
        }
    },
    {
        "path": "input/характеристика.docx",
        "out":  "характеристика_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "org_adress": "АдрессОрганизации",
            "INN": "ОргИНН",
            "fio": "ФИО",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "RukProfOrg": "РукПрофОрг",
            "Date": "СегодняшняяДата"
        }
    },
]
